services:
  ourcity.api.prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - ourcity.postgres.prod
      - ourcity.redis.prod
  ourcity.postgres.prod:
    image: postgres:16.10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ourcity
    ports:
      - "6666:5432"
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
  ourcity.redis.prod:
    image: redis:7.4.5
    ports:
      - "6379:6379"

volumes:
  prod_postgres_data: