# build stage
FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json .
RUN npm ci

COPY . .
RUN npm run build

# test stage
FROM build AS test

WORKDIR /app

RUN npm run test

# prod stage
FROM nginx:1.28-alpine AS prod

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]